### ISSUE TITLE
Angular 5 Error using IE 11

### ISSUE THREAD

**Issue by Chandu200881** [pauldijou/jwt-client#8]
having  "zone.js": "^0.8.26" configuration, Error thrown as
name: "TypeError"
number: -2147418113
stack: "TypeError: Invalid calling object
at scheduleTask (http://localhost:18090/node_modules/zone.js/dist/zone.js:2964:13).

Code in Zone.js file at Line # 2946 is
oriAddListener.call(target, READY_STATE_CHANGE, newListener);

**Comment by pauldijou** [comment]
I don't even see one line related to this lib in your report... I have no idea where to begin looking for a bug.

**Comment by Chandu200881** [comment]
```
Error: Invalid calling object
  Instantiating http://localhost:53635/systemjs-angular-loader.js
  Loading http://localhost:53635/systemjs-angular-loader.js
  Instantiating http://localhost:53635/clientapp/main.js
  Loading /clientapp/main.js
   {
      [functions]: ,
      __proto__: { },
      description: "Invalid calling object
  Instantiating http://localhost:53635/systemjs-angular-loader.js
  Loading http://localhost:53635/systemjs-angular-loader.js
  Instantiating http://localhost:53635/clientapp/main.js
  Loading /clientapp/main.js",
      message: "Invalid calling object
  Instantiating http://localhost:53635/systemjs-angular-loader.js
  Loading http://localhost:53635/systemjs-angular-loader.js
  Instantiating http://localhost:53635/clientapp/main.js
  Loading /clientapp/main.js",
      name: "Error",
      originalErr: {
         [functions]: ,
         __proto__: { },
         description: "Invalid calling object",
         message: "Invalid calling object",
         name: "TypeError",
         number: -2147418113,
         stack: "TypeError: Invalid calling object
   at scheduleTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:2964:13)
   at ZoneDelegate.prototype.scheduleTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:407:21)
   at Zone.prototype.scheduleTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:232:17)
   at Zone.prototype.scheduleMacroTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:255:13)
   at scheduleMacroTaskWithCurrentZone (http://localhost:53635/node_modules/zone.js/dist/zone.js:1114:5)
   at Anonymous function (http://localhost:53635/node_modules/zone.js/dist/zone.js:3001:17)
   at proto[name] (http://localhost:53635/node_modules/zone.js/dist/zone.js:1394:17)
   at Anonymous function (http://localhost:53635/node_modules/systemjs/dist/system.src.js:1528:5)
   at ZoneAwarePromise (http://localhost:53635/node_modules/zone.js/dist/zone.js:891:29)
   at xhrFetch (http://localhost:53635/node_modules/systemjs/dist/system.src.js:1480:3)",
         Symbol()_m.smq5s2735js: undefined,
         Symbol()_n.smq5s2735js: undefined,
         Symbol()_o.smq5s2735js: undefined,
         Symbol()_p.smq5s2735js: undefined,
         Symbol()_q.smq5s2735js: undefined,
         Symbol()_r.smq5s2735js: undefined,
         Symbol()_s.smq5s2735js: undefined,
         Symbol()_t.smq5s2735js: undefined,
         Symbol()_u.smq5s2735js: undefined,
         Symbol()_v.smq5s2735js: undefined
      },
      stack: "TypeError: Invalid calling object
   at scheduleTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:2964:13)
   at ZoneDelegate.prototype.scheduleTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:407:21)
   at Zone.prototype.scheduleTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:232:17)
   at Zone.prototype.scheduleMacroTask (http://localhost:53635/node_modules/zone.js/dist/zone.js:255:13)
   at scheduleMacroTaskWithCurrentZone (http://localhost:53635/node_modules/zone.js/dist/zone.js:1114:5)
   at Anonymous function (http://localhost:53635/node_modules/zone.js/dist/zone.js:3001:17)
   at proto[name] (http://localhost:53635/node_modules/zone.js/dist/zone.js:1394:17)
   at Anonymous function (http://localhost:53635/node_modules/systemjs/dist/system.src.js:1528:5)
   at ZoneAwarePromise (http://localhost:53635/node_modules/zone.js/dist/zone.js:891:29)
   at xhrFetch (http://localhost:53635/node_modules/systemjs/dist/system.src.js:1480:3)",
      Symbol()_m.smq5s2735js: undefined,
      Symbol()_n.smq5s2735js: undefined,
      Symbol()_o.smq5s2735js: undefined,
      Symbol()_p.smq5s2735js: undefined,
      Symbol()_q.smq5s2735js: undefined,
      Symbol()_r.smq5s2735js: undefined,
      Symbol()_s.smq5s2735js: undefined,
      Symbol()_t.smq5s2735js: undefined,
      Symbol()_u.smq5s2735js: undefined,
      Symbol()_v.smq5s2735js: undefined
   }
```

**Comment by pauldijou** [comment]
I don't see any line related to this project. Are you sure the issue is from `jwt-client`?
